---
# tasks file for deploy-configs
- name: find if zk tar file exists
  stat:
   path: /etc/apache-zookeeper-3.6.1.tar.gz
  register: zk_file_exists
  tags:
   - deploy-zk
- name: find if zk dir exists
  stat:
   path: /etc/apache-zookeeper-3.6.1
  register: zk_dir_exists
  tags:
   - deploy-zk
- name: install tar file
  get_url:
   url: "https://archive.apache.org/dist/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz"
   force: yes
   unsafe_writes: yes
   validate_certs: no
   dest: /etc
   owner: hadoop
   group: hadoop
  when: zk_file_exists.stat.exists == false
  tags:
   - deploy-zk
- name: uncompress tar
  unarchive:
   src: /etc/apache-zookeeper-3.6.1-bin.tar.gz
   dest: /etc
   owner: hadoop
   group: hadoop
   remote_src: yes
  when: zk_dir_exists.stat.exists == false
  tags:
   - deploy-zk
- name: permissions
  file:
   path: /etc/apache-zookeeper-3.6.1-bin
   state: directory
   recurse: yes
   owner: hadoop
   mode: 0755
  tags:
   - deploy-zk
- name: create link
  file:
   src: /etc/apache-zookeeper-3.6.1-bin
   dest: /etc/zk
   owner: hadoop
   group: hadoop
   mode: 0755
   state: link
  tags:
   - deploy-zk
- name: permissions for link
  file:
   path: /etc/zk
   state: directory
   recurse: yes
   owner: hadoop
   group: hadoop
   mode: 0755
  tags:
   - deploy-zk
- name: create directory for keeping namenode meta on zk
  file:
   path: /data
   owner: hadoop
   group: hadoop
   mode: 0755
   state: directory
- name: create directory for zk config
  file:
   path: /home/hdfs/data/zookeeper
   owner: hadoop
   group: hadoop
   mode: 0755
   state: directory
- name: copy zoo.cfg
  copy:
   src: zoo.cfg
   dest: /etc/zk/conf/zoo.cfg
   owner: hadoop
   group: hadoop
   mode: 0644
