---
# tasks file for deploy-configs
- name: find if tar file exists
  stat:
   path: /etc/hadoop-3.1.3.tar.gz
  register: path_exists
  tags:
   - deploy-hadoop
   - deploy-wn
- name: find if dir exists
  stat:
   path: /etc/hadoop-3.1.3
  register: dir_exists
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: install tar file
  get_url:
   url: "http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz"
   force: yes
   unsafe_writes: yes
   validate_certs: no
   dest: /etc
   owner: hadoop
   group: hadoop
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
#  when: not path_exists.stat.exists
- name: uncompress tar
  unarchive:
   src: /etc/hadoop-3.1.3.tar.gz
   dest: /etc
   owner: hadoop
   group: hadoop
   remote_src: yes
  when: dir_exists.stat.exists == False
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: permissions
  file:
   path: /etc/hadoop-3.1.3
   state: directory
   recurse: yes
   owner: hadoop
   group: hadoop
   mode: 0755
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: create link
  file:
   src: /etc/hadoop-3.1.3
   dest: /etc/hadoop
   owner: hadoop
   group: hadoop
   mode: 0755
   state: link
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: permissions for link
  file:
   path: /etc/hadoop
   state: directory
   recurse: yes
   owner: hadoop
   group: hadoop
   mode: 0755
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: create nn dir
  file:
    path: /home/hdfs/data/nameNode
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0755
  tags:
    - ["deploy-hadoop"]
- name: create dn dir
  file:
    path: /home/hdfs/data/dataNode
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0755
  tags:
    - ["deploy-wn"]
- name: create edits dir
  file:
    path: /mnt/data1/edits
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0755
  tags:
    - ["deploy-hadoop"]

- name: copy configs
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'core-site.xml', dest: '/etc/hadoop/etc/hadoop/core-site.xml'}
    - { src: 'hdfs-site.xml', dest: '/etc/hadoop/etc/hadoop/hdfs-site.xml'}
    - { src: 'hadoop-env.sh', dest: '/etc/hadoop/etc/hadoop/hadoop-env.sh'}
  tags:
   - ["deploy-hadoop"]
   - ["deploy-wn"]
- name: namenode format
  become_user: hadoop
  command: "{{item}}"
  with_items:
    - "/etc/hadoop/bin/hdfs --daemon stop namenode"
    - "/etc/hadoop/bin/hadoop namenode -format -noninteractive"
    - "/bin/sleep 10"
    - "/etc/hadoop/sbin/start-all.sh"
  tags:
    - ["deploy-hadoop"]
