---
- hosts: nn,wn
  become: true
#  become_method: sudo
  tasks: 
   - name: find if tar file exists
     stat:
       path: /etc/hadoop-3.1.3.tar.gz
     register: path_exists
   - name: find if dir exists
     stat:
       path: /etc/hadoop-3.1.3
     register: dir_exists
   - name: install tar file
     get_url:
       url: "http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz"
       force: yes
       unsafe_writes: yes
       validate_certs: no
       dest: /etc
       owner: hadoop
     when: not path_exists.stat.exists
   - name: uncompress tar
     unarchive:
       src: /etc/hadoop-3.1.3.tar.gz 
       dest: /etc
       owner: hadoop
       remote_src: yes
     when: dir_exists.stat.exists == False
   - name: permissions
     file:
       path: /etc/hadoop-3.1.3
       state: directory
       recurse: yes
       owner: hadoop
       mode: 0755
   - name: create link
     file:
       src: /etc/hadoop-3.1.3
       dest: /etc/hadoop
       owner: hadoop
       mode: 0755
       state: link
   - name: permissions for link
     file:
       path: /etc/hadoop
       state: directory
       recurse: yes
       owner: hadoop
       mode: 0755
   - name: clean uninstall
     file:
       path: /etc/hadoop
       state: absent
     tags:
       - clean
   - name: clean tar
     file:
       path: /etc/hadoop-3.1.3
       state: absent
     tags:  
       - clean
   - name: clear tar1
     file: 
       path: /etc/hadoop-3.1.3.tar.gz
       state: absent
     tags:
       - clean
