---
- hosts: nn,wn
  become: true
  tasks: 
   - name: find if tar file exists
     stat:
       path: /etc/hadoop-3.1.3.tar.gz
     register: path_exists
     tags:
       - deploy 
   - name: find if dir exists
     stat:
       path: /etc/hadoop-3.1.3
     register: dir_exists
     tags:
       - deploy 
   - name: find if zk tar file exists
     stat: 
       path: /etc/apache-zookeeper-3.6.1.tar.gz
     register: zk_file_exists
     tags: 
       - deploy-zk
   - name: find if zk dir exists
     stat:
       path: /etc/apache-zookeeper-3.6.1
     register: zk_dir_exists
     tags:
       - deploy-zk
   - name: install tar file
     get_url:
       url: "http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz"
       force: yes
       unsafe_writes: yes
       validate_certs: no
       dest: /etc
       owner: hadoop
       group: hadoop    
     tags:
       - deploy 
#     when: not path_exists.stat.exists
   - name: uncompress tar
     unarchive:
       src: /etc/hadoop-3.1.3.tar.gz 
       dest: /etc
       owner: hadoop
       group: hadoop
       remote_src: yes
     when: dir_exists.stat.exists == False
     tags:
       - deploy 
   - name: permissions
     file:
       path: /etc/hadoop-3.1.3
       state: directory
       recurse: yes
       owner: hadoop
       group: hadoop
       mode: 0755
     tags:
       - deploy 
   - name: create link
     file:
       src: /etc/hadoop-3.1.3
       dest: /etc/hadoop
       owner: hadoop
       group: hadoop
       mode: 0755
       state: link
     tags:
       - deploy 
   - name: permissions for link
     file:
       path: /etc/hadoop
       state: directory
       recurse: yes
       owner: hadoop
       group: hadoop
       mode: 0755
     tags:
       - deploy 
   - name: install tar file
     get_url:
       url: "http://mirror.cogentco.com/pub/apache/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1.tar.gz"
       force: yes
       unsafe_writes: yes
       validate_certs: no
       dest: /etc
       owner: hadoop
       group: hadoop
     when: zk_file_exists.stat.exists == false
     tags:
       - deploy-zk
   - name: uncompress tar
     unarchive:
       src: /etc/apache-zookeeper-3.6.1.tar.gz
       dest: /etc
       owner: hadoop
       group: hadoop
       remote_src: yes
     when: zk_dir_exists.stat.exists == false
     tags:
       - deploy-zk
   - name: permissions
     file:
       path: /etc/apache-zookeeper-3.6.1
       state: directory
       recurse: yes
       owner: hadoop
       mode: 0755
     tags:
       - deploy-zk
   - name: create link
     file:
       src: /etc/apache-zookeeper-3.6.1
       dest: /etc/zk
       owner: hadoop
       group: hadoop
       mode: 0755
       state: link
     tags:
       - deploy-zk
   - name: permissions for link
     file:
       path: /etc/zk
       state: directory
       recurse: yes
       owner: hadoop
       group: hadoop
       mode: 0755
     tags:
       - deploy-zk
   - name: create nn dir
     file:
       path: /home/hdfs/data/nameNode
       state: directory
       owner: hadoop
       group: hadoop
       mode: 0755
     tags:
       - deploy 
   - name: create edits dir
     file:
       path: /home/hdfs/data/edits
       state: directory
       owner: hadoop
       group: hadoop
       mode: 0755
     tags:
       - deploy 
   - name: install packages
     yum: name = {{item}} state=installed
     with_items:
       - net-tools  
     tags:
       - deploy 
   - name: manage services
     service: name= {{item}} state=stopped enabled=no
     with_items:
       - firewallcmd
     tags:
       - deploy 
   - name: clean uninstall
     file:
       path: /etc/hadoop
       state: absent
     tags:
       - clean
   - name: clean tar
     file:
       path: /etc/hadoop-3.1.3
       state: absent
     tags:  
       - clean
   - name: clear tar1
     file: 
       path: /etc/hadoop-3.1.3.tar.gz
       state: absent
     tags:
       - clean
