###pending completion
###pending testing
###pending deployment and validation
---
- hosts: nn,wn
  become: True
  tasks:
   - name: copy jdk14
     copy:
      src: /Users/sameergawande/Downloads/jdk-14.0.1_linux-x64_bin.rpm
      dest: /tmp/
     ignore_errors: True
   - name: install jdk14
     yum:
      name: /tmp/jdk-14.0.1_linux-x64_bin.rpm
      state: present
   - name: verify hadoop user
     command: id hadoop
     register: user_status
     ignore_errors: True
   - name: add hadoop user
     user:
      name: hadoop
      shell: /bin/bash
     when: user_status.stdout.find("no such user") != 0
   - name: check if tar exists
     stat:
      path: /data/hadoop-3.1.3.tar.gz
     register: tar_exists
   - name: check if dir exists
     stat:
      path: /data/hadoop-3.1.3
     register: dir_exists
   - name: download tar
     get_url: 
      url: http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz
      dest: /data/
      owner: hadoop
     when: not tar_exists.stat.exists
   - name: untar the file
     unarchive:
      src: /data/hadoop-3.1.3.tar.gz
      dest: /data
      remote_src: yes    
     when: dir_exists.stat.exists==False
   - name: create links
     file:
      src: /data/hadoop-3.1.3
      dest: /data/hadoop
      mode: 0755
      owner: hadoop
      state: link
   - name: directory for namenode, edits
     file:
      path: '/data/hdfs/data/{{item}}'
      state: directory
      mode: 0755
      owner: hadoop
     with_items:
      - edits 
      - nameNode 
   - name: remove packages
     yum: 
      name: ['jdk-14.0.1.x86_64'] 
      state: absent
     tags:
      - clean-reset
   - name: remove dir and files
     file:
      path: "{{ item }}"
      state: absent
     with_items:
      - /data/hadoop
      - /tmp/jdk-14.0.1_linux-x64_bin.rpm
      - /data/hadoop-3.1.3.tar.gz
      - /data/hadoop-3.1.3
      - /var/spool/mail/hadoop
      - /data/hdfs
     tags:
      - clean-reset
   - name:
     user:
      name: hadoop
      state: absent
      remove: yes
     tags:
      - clean-reset
