---
- hosts: wn,nn
  become: True
  tasks:
   - name: verify tar file exists
     stat:
      path: /etc/hadoop-3.1.3.tar.gz
     register: file_exists
     tags:  
      - download_software
   - name: verify directory exists
     stat:
      path: /etc/hadoop-3.1.3
     register: directory_exists
     tags:  
      - download_software
   - name: download tar
     get_url:
      url: http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz
      dest: /etc/
      owner: hadoop
      group: hadoop
     when:
      file_exists.stat.exists == False
     tags:
      - download_software
   - name: uncompress software
     unarchive:
      src: /etc/hadoop-3.1.3.tar.gz
      dest: /etc/hadoop-3.1.3
      remote_src: yes
      owner: hadoop
      group: hadoop
      mode: 0755
     when:
      directory_exists.stat.exists == False
   - name: create links for the hadoop directory
     file:
      src: /etc/hadoop-3.1.3
      dest: /etc/hadoop
      owner: hadoop
      group: hadoop
      state: link
 
