---
hosts: nn,wn
become: True
tasks:
 - name: check if tar exists
   stat:
    path: /data/hadoop-3.1.3.tar.gz
   register: tar_exists
 - name: check if dir exists
   stat:
    path: /data/hadoop-3.1.3
   register: dir_exists

 - name: download tar
 - name: untar the file
 - name: create links
