---
- hosts: wn,nn
  become: True
  tasks:
   - name: verify tar file exists
     stat:
      path: /etc/hadoop-3.3.1.tar.gz
     register: file_exists
     tags:  
      - download_software
   - name: verify directory exists
     stat:
      path: /etc/hadoop-3.3.1
     register: directory_exists
     tags:  
      - download_software
   - name: download tar
     get_url:
      url: http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.3.1.tar.gz
      dest: /etc/
      owner: root
     when:
      file_exists.stat.exists == false
     tags:
      - download_software
   - name: uncompress software
     unarchive:
      src: /etc/hadoop-3.3.1.tar.gz
      dest: /etc/
      remote_src: yes
      owner: root
      mode: 0755
     when:
       directory_exists.stat.exists == false
   - name: create links for the hadoop directory
     file:
      src: /etc/hadoop-3.3.1
      dest: /etc/hadoop
      owner: hadoop
      group: hadoop
      state: link
