--- 
- hosts: nn,wn
  become: True
  ignore_errors: true
  tasks: 
   - name: check if user exists
     shell: "id hadoop"
     register: user_result
     ignore_errors: True
   - name: check if group exists
     shell: "groups hadoop"
     register: group_result
     ignore_errors: True
   - name: add user if user does not exist
     user:
      name: hadoop
      shell: /bin/bash
     when: "'no such user' in user_result.stderr"
   - name: create dir
     file:
       path: /home/hadoop/.ssh
       state: directory
       owner: hadoop
       group: hadoop
       mode: 0700
   - name: copy keys
     copy: src={{item.src}} dest={{item.dest}} 
     with_items: 
       - { src: 'hadoop-keys/id_rsa', dest: '/home/hadoop/.ssh/id_rsa'}
       - { src: 'hadoop-keys/id_rsa.pub', dest: '/home/hadoop/.ssh/id_rsa.pub'}
       - { src: 'hadoop-keys/authorized_keys', dest: '/home/hadoop/.ssh/authorized_keys'}
   - name: add group if user does not exist
     group:
      name: hadoop
      state: present
     when: "('groups: hadoopa: no such user' in group_result.stderr)"
