---
- hosts: nn
  become: true
  become_method: sudo
  tasks: 
   - name: install tar file
     get_url:
       url: http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.3.tar.gz
       dest: /etc/
       owner: hadoop
   - name: uncompress tar
     unarchive:
       src: /etc/hadoop-3.1.3.tar.gz 
       dest: /etc
       owner: hadoop
       remote_src: yes
   - name: permissions
     file:
       path: /etc/hadoop-3.1.3
       state: directory
       recurse: yes
       owner: hadoop
       mode: 0755
   - name: create link
     file:
       src: /etc/hadoop-3.1.3
       dest: /etc/hadoop
       owner: hadoop
       mode: 0755
       state: link
   - name: permissions for link
     file:
       path: /etc/hadoop
       state: directory
       recurse: yes
       owner: hadoop
       mode: 0755
