---
- hosts: wn
  become: true
  tasks:
    - name: 
      file:
        path: /home/hdfs/data/dataNode
        state: directory
        owner: hadoop
        group: hadoop
        mode: 0755
      tags: 
        - reset

    - name:
      become_user: hadoop
      command: "{{ item }}"
      with_items:
        /etc/hadoop/bin/hdfs --daemon stop datanode
#        /etc/hadoop/bin/hdfs format -datanode
        /etc/hadoop/bin/hdfs --daemon start datanode
      tags: 
        - reset
