---
- hosts: all
  become: true
  tasks:
   - name: stop hadoop services
     command: "/etc/hadoop/bin/hdfs --daemon stop namenode"
     become: yes
     become_user: hadoop
     tags:
     # - reset-all
      - reset-zkfs
     
   - name: remove hadoop user
     user: 
       name: hadoop
       force: yes
       state: absent
       remove: yes
     tags:
      - reset-all

   - name: remove hadoop group
     group: 
       name: hadoop
       state: absent
     tags:
      - reset-all

   - name: remove files
     file: 
       path: "{{item}}"
       state: absent
     with_items:
       - /etc/hadoop
       - /etc/hadoop-3.1.4
       - /etc/hadoop-3.1.4.tar.gz
       - /home/hadoop/
       - /home/hdfs
       - /opt/zookeeper
       - /home/zk
       - /etc/zk
       - /data/mycluster
       - /mnt/data1/edits
       - /etc/apache-zookeeper-3.6.1.tar.gz
       - /etc/apache-zookeeper-3.6.1
       - /etc/apache-zookeeper-3.6.1-bin.tar.gz
       - /etc/apache-zookeeper-3.6.1-bin
     tags:
      - reset-all
 
   - name: clean packages
     yum:
       name: "{{item}}"
       state: absent
     with_items:
       - java-1.8.0
       - copy-jdk-configs-3.3-10
       - java-1.7.0
       - jdk-14.0.1
       - java-1.7.0-openjdk-headless
       - java-1.8.0-openjdk-headless
       - copy-jdk-configs
     tags:
      - reset-all
     
   - name: remove zkfs journalnode files
     file: 
       path: "{{item}}"
       state: absent
     with_items:
       - /data/mycluster
     tags:
      - reset-zkfc
   - name: start journalnode
     command: "{{item}}"
     with_items:
       - /etc/hadoop/bin/hdfs --daemon stop journalnode 
       - /etc/hadoop/bin/hdfs --daemon start journalnode 
     become: yes
     become_user: hadoop
     tags:
      - reset-zkfc
   - name: set up first namenode
     command: "{{item}}"
     with_items:
       - /etc/hadoop/bin/hdfs namenode -format -nonInteractive
       - /etc/hadoop/bin/hdfs --daemon start namenode
       - /etc/hadoop/bin/hdfs zkfc formatZK
     command: "/etc/hadoop/bin/hdfs namenode -format -nonInteractive"
     become: yes
     become_user: hadoop
     run_once: true
     tags:
      - reset-zkfc
   - name: start zkfs
     command: "{{item}}"
     with_items: 
       - /etc/hadoop/bin/hdfs --daemon start zkfc
     become: yes
     become_user: hadoop
     tags:
      - reset-zkfc
